### ISSUE TITLE
easyeffects fail to load

### ISSUE THREAD

**Issue by ja66** [p-chan5/EasyPulse#1]
All easyeffects fail to load due to '#0' in each json tag. Unfortunately I cannot push a new branch to create a pull request, therefore here's how I fixed it locally on mu Fedora 36  system:

```bash
find easyeffects -type f -exec sed -i 's/#0//g' {} \;
```

Would be nice if you could apply my fix

**Comment by p-chan5** [comment]
Hi. What version of EasyEffects are you using? The `#` was added to `7.0.0` since [you can now add more than one effect](https://github.com/wwmm/easyeffects/blob/master/CHANGELOG.md#700). i.e. `equalizer#0` `equalizer#1` Since I work with the current stable branch, it is impossible for me to support old versions. That's why I recommend [rebuilding them](https://github.com/p-chan5/EasyPulse/wiki/HOW-TO-BUILD-THEM) to avoid these or other problems.

For now, I think your solution is only good for you. Still, make sure the other effects are still working and not broken.

**Comment by ja66** [comment]
I'm on Fedora 37 which delivers 
```
Last metadata expiration check: 0:01:04 ago on Sa 01 Apr 2023 08:48:56 CEST.
Installed Packages
Name         : easyeffects
Version      : 6.3.0
Release      : 1.fc37
Architecture : x86_64
Size         : 4.7 M
Source       : easyeffects-6.3.0-1.fc37.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Audio effects for PipeWire applications
URL          : https://github.com/wwmm/easyeffects
License      : GPLv3+
Description  : Limiters, compressor, reverberation, high-pass filter, low pass filter,
             : equalizer many more effects for PipeWire applications.
```
I see that https://github.com/wwmm/easyeffects has v7.0.1 available. I'm going to update

**Comment by p-chan5** [comment]
You can also download [0.2.0](https://github.com/p-chan5/EasyPulse/releases/tag/0.2.0) It was the last release where I supported `6.3.0`

However, I've made many changes since then (including bug fixes) that might make it obsolete (I mean my settings, not the tool itself, it still works as expected).

In the future I will take advantage of this feature (more of an effect) so if you can, update and wait for news :)
